upstream_project_url: https://github.com/matiasb/python-unidiff
upstream_ref: v*
issue_repository: https://github.com/mfocko/python-unidiff

downstream_package_name: python-unidiff
specfile_path: .distro/python-unidiff.spec

patch_generation_ignore_paths:
- .distro
patch_generation_patch_id_digits: 1

sync_changelog: true

files_to_sync:
- src: .distro/
  dest: .
  delete: true
  filters:
  - protect .git*
  - protect sources
  - exclude source-git.yaml
  - exclude .gitignore

srpm_build_deps: []

jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - fedora-branched
    - epel-all

- job: koji_build
  trigger: commit
  metadata:
    dist_git_branches:
    - fedora-branched
    - epel-all

- job: bodhi_update
  trigger: commit
  metadata:
    dist_git_branches:
    - fedora-branched
    - epel-all

- job: copr_build
  trigger: commit
  metadata:
    branch: rawhide
    targets:
    - fedora-all
    - epel-all
    owner: mfocko
    project: python-unidiff
    preserve_project: True
